version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_CLIENT=mongodb://mongodb:27017
  scheduler:
    image: tosanchez/atsc-meetings:scheduler-dev
    environment:
      - SPRING_APPLICATION_NAME=Scheduler
      - SERVER_PORT=8080
      - SPRINGDOC_SWAGGER_UI_PATH=/scheduler-docs
    ports:
      - "8080:8080"
    depends_on:
      - auth
  gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "80:80"
    environment:
      - 'GATEWAY_SERVICES=[{"name": "Auth", "base_url": "http://auth:8000"},
      {"name": "Scheduler", "base_url": "http://scheduler:8080", "readiness_url": "/actuator/health"}]'
      - REDIS_HOST=redis://redis:6379
      - FASTAPI_USE_LIMITER=1
      - FASTAPI_LIMITER_THRESHOLD=10
      - FASTAPI_LIMITER_INTERVAL=60
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth
      - scheduler

volumes:
  cache:
    driver: local