version: '3'
services:
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  scheduler:
    image: tosanchez/atsc-meetings:scheduler-dev
    environment:
      - SPRING_APPLICATION_NAME=Scheduler
      - SPRINGDOC_SWAGGER_UI_PATH=/scheduler-docs
    ports:
      - "8080:8080"
    depends_on:
      - auth
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth
      - scheduler