server:
  port: 8001

spring:
  data:
    mongodb:
      uri: mongodb+srv://lean:Lean123456@cluster0.8jk604t.mongodb.net/meetings
      database: meetings
  application:
    name: Scheduler

springdoc:
  swagger-ui:
    path: /docs
  show-actuator: true
  enable-kotlin: true