server:
  port: 8001

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_NAME}
  application:
    name: Scheduler

springdoc:
  swagger-ui:
    path: /scheduler-docs
  show-actuator: true
  enable-kotlin: true