# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: API Gateway Build

on:
  push:
    branches: '*'
    paths:
      - 'api-gateway/app/**'
      - 'api-gateway/tests/**'

  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'api-gateway/app/**'
      - 'api-gateway/tests/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api-gateway

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest
      - name: Build Image
        run: |
          docker build . --file Dockerfile --tag gateway:dev